global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['eigenda-native-node:<NODE_METRICS_PORT>']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'scraper'
    scrape_interval: 1m
    static_configs:
      - targets: ['scraper:9600']