{
 "title": "EigenDA",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "EigenDA number of accumulated batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_eigenda_batches_total{type=\"number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA size of accumulated batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_eigenda_batches_total{type=\"size\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of current batches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_eigenda_current_batches{type=\"number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA size of current batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_current_batches{type=\"size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency StoreChunks (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_request_latency_ms{quantile=\"0.99\", method=\"StoreChunks\"}",
     "legendFormat": "p99 {{stage}}"
    },
    {
     "expr": "node_request_latency_ms{quantile=\"0.95\", method=\"StoreChunks\"}",
     "legendFormat": "p95 {{stage}}"
    }
   ]
  },
  {
   "title": "Average batch size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_eigenda_current_batches{type=\"size\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(node_eigenda_current_batches{type=\"size\"}[$__rate_interval])\n/\ncount_over_time(node_eigenda_current_batches{type=\"size\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA StoreChunks RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_eigenda_rpc_requests_total{method=\"StoreChunks\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency RetrieveChunks (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_request_latency_ms{quantile=\"0.99\", method=\"RetrieveChunks\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "node_request_latency_ms{quantile=\"0.95\", method=\"RetrieveChunks\"}",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Total Socket updates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_eigenda_node_socket_updates_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA RetrieveChunks RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_eigenda_rpc_requests_total{method=\"RetrieveChunks\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(status) (rate(node_eigenda_batches_total{type=\"number\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}